FROM node:15.4-alpine3.12

ENV MONGO_DB_USERNAME=mongo-admin \
  MONGO_DB_PWD=incorrect

RUN mkdir -p /home/app

COPY ./app /home/app

# set default dir so that next commands executes in /home/app dir
WORKDIR /home/app

# will execute npm install in /home/app because of WORKDIR
RUN npm install

# no need for /home/app/server.js because of WORKDIR
CMD ["node", "server.js"]
