version: '3'

services:
  mongodb:
    image: mongo # image to pull mongodb

    ports:
      - 27017:27017 # Host:Container
    environment: # Environment variables
      - MONGO_INITDB_ROOT_USERNAME=mongo-admin
      - MONGO_INITDB_ROOT_PASSWORD=incorrect

  mongo-express:
    image: mongo-express # image to pull mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo-admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=incorrect
      - ME_CONFIG_MONGODB_SERVER=mongodb # to which server it is connected
